name: OWASP Dependency-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Executa o OWASP Dependency-Check usando a ação oficial
      - name: Run OWASP Dependency-Check
        uses: dependency-check/dependency-check-action@v4.3.2
        with:
          project-name: 'Node.js Project'
          path: '.'
          format: 'HTML'
          out: 'dependency-check-report.html'
          args: >
            --enableExperimental
            --failOnCVSS 7

      # Faz upload do relatório gerado como artefato
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html
