name: OWASP Dependency-Check

on:
  push:
    branches:
      - '*' # Executa em qualquer branch para push
  pull_request:
    branches:
      - '*' # Executa em qualquer branch para pull request

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Atualizado para a versão mais recente
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired
            --enableExperimental # Adicionado para suportar Node.js
      - name: Upload Test results
        uses: actions/upload-artifact@v4 # Atualizado para a versão mais recente
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/reports
