name: OWASP Dependency-Check

on: [push, pull_request]

jobs:
  depcheck:
    name: Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run OWASP Dependency-Check
        uses: stevespringett/dependency-check-action@main
        with:
          project: 'NestJS Project'
          path: './'
          format: 'HTML'
          out: 'dependency-check-report'
          args: >
            --enableExperimental
            --nodePackageSkipDevDependencies
            --failOnCVSS 7

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/dependency-check-report.html
